source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'DoggoStylo2.0' do
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod "GSImageViewerController"
  pod "DBDebugToolkit"
end
